import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/navbar/Navbar'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
  weight: ['400', '500', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${inter.variable} antialiased h-dvh flex flex-col text-start items-start justify-start`}
        > 
        <div className='flex flex-col w-full h-fit pb-[1.4rem]'>
          <Navbar />
        </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
